### ISSUE TITLE
Reliability should be grouped together under one major section

### ISSUE THREAD

**Issue by remomueller** [sleepepi/mesa-documentation#1]
Currently, Reliability is split across two major (hundred-level) sections. We should combine these into one major section, and create two corresponding minor sections for PSG Summary and Actigraphy.

Currently: 
- 400 Reliability MESA PSG Summary
- 500 Reliability MESA Actigraphy

After:
- 400 Reliability
  - 410 Reliability MESA PSG Summary
  - 420 Reliability MESA Actigraphy

**Comment by mrueschman** [comment]
Closing issue and deleting this repository. Eventually this information transitioned into the [NSRR mesa-documentation repository](https://github.com/nsrr/mesa-documentation/).
